[package]
name = "diesel_logger"
version = "0.3.0"
authors = [
    "Josh Holmer <jholmer.in@gmail.com>",
    "Aleksey Zholobenko",
    "Georg Semmler"
]
description = "Times and logs queries executed by diesel. Adapted for GST."
exclude = [
    "tests/*",
]
homepage = "https://github.com/shssoichiro/diesel-logger"
license = "MIT"
repository = "https://github.com/shssoichiro/diesel-logger"
edition = "2018"

[badges]
maintenance = { status = "as-is" }

[dependencies]
log = "0.4.1"
chrono = "0.4.11"

[dependencies.diesel]
default-features = false
features = ["extras"]
git = "https://github.com/diesel-rs/diesel"
rev = "fa826f0c97e1f47eef34f37cb5b60056855a2b9a"
